name: Hexo-make

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Shanghai"

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: yarn install and setup env
      run: |
        yarn install

    - name: Hexo build
      run: |
        yarn build

    - name: copy file to server SZX-CC
      uses: burnett01/rsync-deployments@5.0
      with:
        switches: -avzr --delete
        path: "public/"
        remote_path: ${{ secrets.HTML_PATH }}
        remote_host: ${{ secrets.HOST_SZXCC }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}
